plugin:
  name: editor-tagfilter-defaults
  version: 1.0
  vendor: Programmfabrik GmbH
  server:
    api-version:
      require: 1
  webfrontend:
    url: build/webfrontend/editor-tagfilter-defaults.js
    l10n: build/webfrontend/l10n

base_config:
  - name: editor-tagfilter-defaults
    group: editor
    parameters:
      filters:
        type: table
        fields:
          - name: "operation"
            type: string-list
            label_choice: "operation"
            choices:
              - update
              - insert
          - name: "tagfilter"
            type: "text"
            plugin_type: "tag-filter"
          - name: "mask_id"
            type: "int"
            plugin_type: "mask-select"
          - name: "default"
            type: "text"
            plugin_type: "column-default-value"

